SELECT 
CASE
	WHEN GRADES.GRADE > 7 THEN S.name
        ELSE NULL
        END AS NAME,
       GRADES.GRADE,
       STUDENTS.MARKS
FROM STUDENTS
JOIN GRADE ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER  BY GRADES.GRADE DESC, STUDENTS.NAME, STUDENTS.MARKS;
