SELECT H.HACKER_ID, H.NAME
FROM
  HACKERS H
  INNER JOIN SUBMISSIONS S ON H.HACKER_ID = S.HACKER_ID
  INNER JOIN CHALLENGES C ON S.CHALLENGE_ID = C.CHALLENGE_ID
  INNER JOIN DIFFICULTY D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
WHERE D.SCORE = S.SCORE AND D.DIFFICULTY_LEVEL = C.DIFFICULTY_LEVEL
GROUP BY H.HACKER_ID, H.NAME
HAVING
  COUNT(S.SUBMISSION_ID) > 1
ORDER BY
  COUNT(S.SUBMISSION_ID) DESC, H.HACKER_ID;
