Solution-1: Single Query with UNION

(
SELECT CITY, LENGTH(CITY) AS LEN FROM STATION
ORDER BY LEN, CITY 
LIMIT 1
)
UNION
(
SELECT CITY, LENGTH(CITY) AS LEN FROM STATION
ORDER BY LEN DESC, CITY 
LIMIT 1
)


Solution-2: 2 Separate Queries

SELECT CITY, LENGTH(CITY) AS LEN FROM STATION ORDER BY LEN, CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) AS LEN FROM STATION ORDER BY LEN DESC, CITY LIMIT 1;