Solution-1: Using GROUP BY, ORDER BY & LIMIT

SELECT (SALARY * MONTHS) as MAX_SAL, COUNT(*) FROM EMPLOYEE
GROUP BY MAX_SAL
ORDER BY MAX_SAL DESC
LIMIT 1;


Solution-2: Using GROUP BY & SUB-QUERY

SELECT SALARY*MONTHS, COUNT(*) FROM EMPLOYEE
WHERE (SALARY*MONTHS) = (SELECT MAX(SALARY*MONTHS) FROM EMPLOYEE) 
GROUP BY SALARY*MONTHS;


Solution-3: Using MAX & SUB-QUERY

SELECT MAX(SALARY*MONTHS), COUNT(*)
FROM EMPLOYEE
WHERE (SALARY*MONTHS) = (SELECT MAX(SALARY*MONTHS) FROM EMPLOYEE);
